# Generated by Django 5.1.7 on 2025-03-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('vacation', 'On Vacation'), ('sick', 'Sick Leave'), ('absent', 'Absent')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ManyToManyField(blank=True, to='employees.department'),
        ),
    ]
