# Generated by Django 5.1.7 on 2025-03-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_department_remove_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('holiday', 'Holiday'), ('sick', 'Sick Leave'), ('absent', 'Absent'), ('off', 'Day off')], default='available', max_length=20),
        ),
    ]
